---
- name: "ipmi_exporter | Include packages tasks [for deps]"
  ansible.builtin.import_tasks:
    file: "packages.yml"
  vars:
    ipmi_exporter_pacakges_variant: "{{ lookup('ansible.builtin.vars',
      'ipmi_exporter_packages_deps') }}"
- name: "ipmi_exporter | Download & unarchive exporter binary from tarball"
  ansible.builtin.unarchive:
    src: "{{ lookup('ansible.builtin.vars', 'ipmi_exporter_url') + '/v' +
      lookup('ansible.builtin.vars', 'ipmi_exporter_version') +
      '/ipmi_exporter-' + lookup('ansible.builtin.vars',
      'ipmi_exporter_version') + '.' + lookup('ansible.builtin.vars',
      'ipmi_exporter_arch') + '.tar.gz' }}"
    dest: "{{ lookup('ansible.builtin.vars', 'ipmi_exporter_dest') }}"
    remote_src: "yes"
    include: "{{ 'ipmi_exporter-' + lookup('ansible.builtin.vars',
      'ipmi_exporter_version') + '.' + lookup('ansible.builtin.vars',
      'ipmi_exporter_arch') + '/ipmi_exporter' }}"
    mode: "0775"
    owner: "root"
    group: "root"
- name: "ipmi_exporter | Move exporter binary arfter unarchive"
  ansible.builtin.command:
    cmd: "{{ 'mv ' + lookup('ansible.builtin.vars', 'ipmi_exporter_dest') +
      '/ipmi_exporter-' + lookup('ansible.builtin.vars',
      'ipmi_exporter_version') + '.' + lookup('ansible.builtin.vars',
      'ipmi_exporter_arch') + '/ipmi_exporter ' +
      lookup('ansible.builtin.vars', 'ipmi_exporter_dest') + '/' }}"
    removes: "{{ lookup('ansible.builtin.vars', 'ipmi_exporter_dest') +
      '/ipmi_exporter-' + lookup('ansible.builtin.vars',
      'ipmi_exporter_version') + '.' + lookup('ansible.builtin.vars',
      'ipmi_exporter_arch') + '/ipmi_exporter' }}"
- name: "ipmi_exporter | Deleting unnecessary directory"
  ansible.builtin.file:
    path: "{{ lookup('ansible.builtin.vars', 'ipmi_exporter_dest') +
      '/ipmi_exporter-' + lookup('ansible.builtin.vars',
      'ipmi_exporter_version') + '.' + lookup('ansible.builtin.vars',
      'ipmi_exporter_arch') }}"
    state: "absent"
  diff: false
