---
- name: "ipmi_exporter | Include pre requisite tasks"
  ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- name: "ipmi_exporter | Include dependency installation tasks"
  ansible.builtin.import_tasks:
    file: "dependencies.yml"
  when:
    - "hostvars[inventory_hostname]['ipmi_exporter'] is defined"
    - "hostvars[inventory_hostname]['ipmi_exporter']
      not in ['', [], '[]', None]"
- name: "ipmi_exporter | Include packages tasks [package deployment]"
  ansible.builtin.include_tasks:
    file: "packages.yml"
  when:
    - "hostvars[inventory_hostname]['ipmi_exporter'] is defined"
    - "hostvars[inventory_hostname]['ipmi_exporter']
      not in ['', [], '[]', None]"
    - "hostvars[inventory_hostname]['ipmi_exporter'] |
       community.general.json_query(lookup('ansible.builtin.vars',
      'ipmi_exporter_install_package', default='')) == 'true'"
  vars:
    ipmi_exporter_install_package: "[] |
      map(&install_package || 'false', @) | [0]"
    ipmi_exporter_pacakges_variant:
      "{{ hostvars[inventory_hostname]['ipmi_exporter_package'] }}"
- name: "ipmi_exporter | Include packages tasks [not package deployment]"
  ansible.builtin.include_tasks:
    file: "download.yml"
  when:
    - "hostvars[inventory_hostname]['ipmi_exporter'] is defined"
    - "hostvars[inventory_hostname]['ipmi_exporter']
      not in ['', [], '[]', None]"
    - "hostvars[inventory_hostname]['ipmi_exporter'] |
       community.general.json_query(lookup('ansible.builtin.vars',
      'ipmi_exporter_install_package', default='')) == 'false'"
  vars:
    ipmi_exporter_install_package: "[] |
      map(&install_package || 'false', @) | [0]"
- name: "ipmi_exporter | Include deployment tasks"
  ansible.builtin.import_tasks:
    file: "deploy.yml"
